# Generated by Django 2.0.4 on 2018-04-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('userName', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepperoni', models.BooleanField(default=False)),
                ('sausage', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('canadianBacon', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('eggplant', models.BooleanField(default=False)),
                ('tomatoBasil', models.BooleanField(default=False)),
                ('greenPeppers', models.BooleanField(default=False)),
                ('hamburger', models.BooleanField(default=False)),
                ('spinach', models.BooleanField(default=False)),
                ('artichoke', models.BooleanField(default=False)),
                ('buffaloChicken', models.BooleanField(default=False)),
                ('barbecueChicken', models.BooleanField(default=False)),
                ('anchovies', models.BooleanField(default=False)),
                ('blackOlives', models.BooleanField(default=False)),
                ('freshGarlic', models.BooleanField(default=False)),
                ('zucchini', models.BooleanField(default=False)),
            ],
        ),
    ]
