# Generated by Django 2.0.4 on 2018-04-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180418_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='orderID',
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pizzaOrders', serialize=False, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suborder',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subOrders', serialize=False, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
