# Generated by Django 2.0.4 on 2018-04-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180413_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizzaregular',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizzasicilian',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Category'),
        ),
    ]
