# Generated by Django 2.0.4 on 2018-04-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180418_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('orderNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderNumber',
            new_name='orderNumberCust',
        ),
        migrations.AddField(
            model_name='order',
            name='orderNumberRest',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
