# Generated by Django 2.0.4 on 2018-04-14 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180413_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dinnerPlatters', serialize=False, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pastas', serialize=False, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='pizzaregular',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regularPizzas', serialize=False, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='pizzasicilian',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sicilianPizzas', serialize=False, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salads', serialize=False, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subs', serialize=False, to='orders.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='relatedName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.RelatedName'),
        ),
    ]
