# Generated by Django 2.0.4 on 2018-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180420_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerName',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
