# Generated by Django 2.0.4 on 2018-04-15 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20180414_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderNumber',
            new_name='Customer',
        ),
    ]
