# Generated by Django 2.0.4 on 2018-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180414_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='customerID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='itemID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
