# Generated by Django 2.0.4 on 2018-04-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180414_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orderNumber',
            field=models.IntegerField(default=0),
        ),
    ]
