# Generated by Django 2.0.4 on 2018-04-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180414_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='checkedOut',
        ),
    ]
