# Generated by Django 2.0.4 on 2018-04-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180415_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkedOut',
        ),
    ]
