# Generated by Django 2.0.4 on 2018-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_checkedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='itemName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
