# Generated by Django 2.0.4 on 2018-04-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_itemcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subclass',
        ),
    ]
